### PR TITLE
Fix Undefined variable $isConcealed Error

### PR DESCRIPTION
**Pull request by Harduex**

### CODE REVIEW

**Comment by martin-ro** [comment]
Hi, thanks for the PR. Could you explain what problem the PR fixes?

**Comment by Harduex** [comment]
Hi, I received this error when using the module. 
image
 
After commenting these lines, it works:
image
image

**Comment by martin-ro** [comment]
Can you check what version of Filament you are using? The `isConcealed` check was introduced in [v2.11.12](https://github.com/laravel-filament/filament/releases/tag/v2.11.12)

If you can, just update Filament to the latest version and the error should be gone. Let me know if that works for you.

**Comment by Harduex** [comment]
That worked, thank you :)

**Pull request closed without merging**
